In [38]:
import pandas as pd
import tensorflow as tf
import numpy as np
import random
import warnings
warnings.filterwarnings('ignore')

tf.random.set_seed(42)
np.random.seed(42)
random.seed(42)

In [39]:
## importing the dataset
df = pd.read_csv('data/Churn_Modelling.csv')

In [40]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [41]:
df.shape ## (10000, 14)

(10000, 14)

In [42]:
## The dataset has 10,000 rows and 14 columns.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [43]:
df.isnull().sum() ## There are no missing values in the dataset.

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [44]:
df.describe() ## The dataset has a wide range of values for the numerical variables.

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [45]:
## Preprocess the data
df = df.drop(["RowNumber","CustomerId","Surname",], axis=1) # droping coulmn from the feature

In [46]:
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [47]:
## Feature Scaling and Encoding

## The dataset contains both numerical and categorical variables. We need to encode the categorical variables before we can use them in our machine learning model.
from sklearn.preprocessing import LabelEncoder
import pickle ## Pickle is commonly used to save machine learning models after training, so that they can be loaded and used later without having to retrain the model.



label_encoder_gender =LabelEncoder() ## Encode categorical variables
df['Gender']= label_encoder_gender.fit_transform(df['Gender']) ## This would change the Columns to Zeros(0) and Ones(1)
df.head(5)

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0

In [48]:
## One-hot encode the 'Geography' column
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder()
geo_encoded = encoder.fit_transform(df[['Geography']])
geo_encoded

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [49]:
geo_encoded.toarray() ## Convert the sparse matrix to a dense array

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [50]:
encoder.get_feature_names_out(['Geography'])
geo_encoded_df = pd.DataFrame(geo_encoded.toarray(), columns=encoder.get_feature_names_out(['Geography']))
geo_encoded_df.head()

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0
1               0.0                0.0              1.0
2               1.0                0.0              0.0
3               1.0                0.0              0.0
4               0.0                0.0              1.0

In [51]:
## combine the original dataframe with the one-hot encoded dataframe
df = pd.concat([df.drop('Geography', axis=1), geo_encoded_df], axis=1)
df.head() ## The 'Geography' column has been replaced with three new columns: 'Geography_France', 'Geography_Germany', and 'Geography_Spain', which indicate the presence of each category in the original 'Geography' column.

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [52]:
## Save the enceder for future use
with open('label_encoder_gender.pkl', 'wb') as f:
    pickle.dump(label_encoder_gender, f)

In [53]:
with open('encoder.pkl', 'wb') as f:
    pickle.dump(encoder, f)

In [54]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
## Divide the data to indepent and dependent variable, X--> independent variable and y--> dependent variable
X = df.drop('Exited', axis=1) # Features
y = df['Exited'] # Target variable

## Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [55]:

## standard scaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [56]:
X_train.shape, X_test.shape

((8000, 12), (2000, 12))

In [57]:
with open('scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)

In [58]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
from tensorflow.keras.layers import BatchNormalization
import datetime

In [59]:
(X_train.shape[1],) ## The input shape for the ANN model is (11,)

(12,)

In [60]:
## Building the ANN model
ann_model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)), ## First hidden layer with 64 neurons and ReLU activation function, and input shape equal to the number of features in the training data
    BatchNormalization(), ## Batch normalization layer to normalize the activations of the previous layer
    Dropout(0.2), ## Dropout layer with a dropout rate of 0.5 to prevent overfitting
    Dense(32, activation='relu'), ## Second hidden layer with 32 neurons and ReLU activation function
    Dropout(0.2), ## Dropout layer with a dropout rate of 0.5 to prevent overfitting
    Dense(1, activation='sigmoid') ## Output layer with 1 neuron and sigmoid activation function for binary classification
]

)

In [61]:
ann_model.summary() ## Print the summary of the model architecture

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 64)                832

 batch_normalization_1 (Bat  (None, 64)                256
 chNormalization)

 dropout_2 (Dropout)         (None, 64)                0

 dense_4 (Dense)             (None, 32)                2080

 dropout_3 (Dropout)         (None, 32)                0

 dense_5 (Dense)             (None, 1)                 33

=================================================================
Total params: 3201 (12.50 KB)
Trainable params: 3073 (12.00 KB)
Non-trainable params: 128 (512.00 Byte)
_________________________________________________________________

In [62]:
import tensorflow
opt=tensorflow.keras.optimizers.legacy.Adam(learning_rate=0.001) ## Define the optimizer with a learning rate of 0.01
loss=tensorflow.keras.losses.BinaryCrossentropy() ## Define the loss function for binary classification
loss

In [63]:
## compile the model
ann_model.compile(
    optimizer=tf.keras.optimizers.legacy.Adam(learning_rate=0.001),
    loss='binary_crossentropy',
    metrics=['accuracy']
) 

## Compile the model with Adam optimizer, binary cross-entropy loss function, and accuracy as a metric

In [64]:
## Set up the TensorBoard callback to log training metrics for visualization
log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S") ## Define the log directory for TensorBoard, which includes a timestamp to ensure unique log files for each training run
tensorflow_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)     ## Create a TensorBoard callback that will log training metrics every epoch

In [65]:
## Set up early stopping to prevent overfitting
early_stopping = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True) ## Create an EarlyStopping callback that will monitor the validation loss and stop training if it does not improve for 5 consecutive epochs, and restore the best weights from the epoch with the lowest validation

In [66]:
## Train the mode


history = ann_model.fit(
    X_train, y_train, ## Training data and labels
    validation_data=(X_test, y_test), ## Validation data and labels
    epochs=100, ## Maximum number of epochs to train the model
    callbacks=[early_stopping, tensorflow_callback] ## Callbacks for early stopping and TensorBoard logging
)

Epoch 1/100
250/250 [==============================] - 2s 5ms/step - loss: 0.5687 - accuracy: 0.7284 - val_loss: 0.4309 - val_accuracy: 0.8185
Epoch 2/100
250/250 [==============================] - 1s 4ms/step - loss: 0.5076 - accuracy: 0.7847 - val_loss: 0.4204 - val_accuracy: 0.8150
Epoch 3/100
250/250 [==============================] - 1s 4ms/step - loss: 0.5176 - accuracy: 0.7859 - val_loss: 0.4278 - val_accuracy: 0.8010
Epoch 4/100
250/250 [==============================] - 1s 4ms/step - loss: 0.5435 - accuracy: 0.7822 - val_loss: 0.4211 - val_accuracy: 0.8150
Epoch 5/100
250/250 [==============================] - 1s 4ms/step - loss: 0.5273 - accuracy: 0.7903 - val_loss: 0.5070 - val_accuracy: 0.7970
Epoch 6/100
250/250 [==============================] - 1s 4ms/step - loss: 0.5529 - accuracy: 0.7775 - val_loss: 0.4934 - val_accuracy: 0.8005
Epoch 7/100
250/250 [==============================] - 1s 4ms/step - loss: 0.5314 - accuracy: 0.7849 - val_loss: 0.4472 - val_accuracy: 0.8115

In [67]:
ann_model.save('churn_model.h5') ## Save the trained model to a file named 'churn_model.h5' in the current directory

In [68]:
## Load Tensorboard Extension
# %load_ext tensorboard

In [69]:
# %tensorboard --logdir logs/fit

In [70]:
## Load the pickle files